services:
  site:
    container_name: wallpapers
    image: oven/bun
    ports:
      - 5173:5173
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'bun install && bun dev -- --host'
